### ISSUE TITLE
JDK 11 no longer working, now requires JDK 17

### ISSUE THREAD

**Issue by stonkstuff** [flathub/com.tdameritrade.ThinkOrSwim#11]
Running the application now presents the following:
![image](https://github.com/user-attachments/assets/b88df8c7-e42a-457a-98f7-e9deefe00c45)

I believe that updating the sdk-extensions and modules in the manifest should fix this:

```
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk17
```

```
modules:
  - name: openjdk
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk17/install.sh
```
